version: 2.1

executors:
  kubernetes-executor:
    docker:
      - image: circleci/python:3.8 

jobs:
  build:
    executor: kubernetes-executor
    steps:
      - checkout
      
      - run:
          name: Install Minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && \
            chmod +x minikube && \
            sudo mv minikube /usr/local/bin/
      
      - run:
          name: Start Minikube
          command: |
            minikube start --driver=none

      - run:
          name: Apply Kubernetes Deployment
          command: |
            kubectl apply -f deployment.yaml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
